Force initialization of companion objects for all Courier generated classes
Summary:
The bug	we hot fixed in	https://phabricator.dkandu.me/D22660 occured because a coercer that we expected to be registered in the initializer of the companion object of a Courier generated array class was not registered.

In Pegasus, static class initializers are used to register coercers. If these static class initializers are not executed *before* a class instance is initialized, Pegasus internal marshalling code will fail at runtime with an error like:

```
TemplateOutputCastException: Output KXOLVTovEeWnxw5wP_KHTw is not a and cannot be coerced to org.coursera.opencourse.model.CourseId
```

Courier uses the same basic approach that Pegasus uses, except we register coercers in the initializer of the companion object.

However, Scala companion objects are lazier than Java static class initializers. Note in the below REPL example how the companion object's initializer is executed lazily, when the companion object first needed, not when a class instance is first instantiated. This is totally reasonable behaviour. It is just different from how Java static class initializers work:

```
scala> class Example() { def classMethod() {} }; object Example { println("companion object initializers executed"); def companionObjectMethod() {} }
defined class Example
defined object Example

scala> val example = new Example()
example: Example = Example@75329a49

scala> example.classMethod()

scala> Example.companionObjectMethod()
companion object initializers executed
```

In our particular case, we need to register our coercers before the companion object or any class instances are instantiated.

The best approach I've found in Scala to achieve this is:

```
scala> class Example() { Example; def classMethod() {} }; object Example { println("static initializers executed"); def companionObjectMethod() {} }
defined class Example
defined object Example

scala> val example = new Example()
static initializers executed
example: Example = Example@7a52f2a2
```

(Note that `Example` has been added to the class initializer code).

Ideally we would not register coercers in Courier using initializers at all, since this approach is heavily reliant on side effects. We've mimicked the Pegasus approach up to this point because it allows us to leverage a significant amount of functionality with little effort.  Long term we should look for an alternative that is more Scala idiomatic, maybe provide coercers via implicits?

Test Plan: Added unit tests.

Reviewers: danchia

Subscribers: rsumbaly, yang, saeta