Go to Courier definition action failing with NoClassDefFoundError
Since IntelliJ IDEA 2019.2 release, the Java functionality was extracted as a separate plugin. Therefore it needs to be declared as a dependency.

More info: https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/